// Type Coercion
console.log("Type Coercion")
console.log(0 == false)
console.log(0 == true)
console.log("0" == false)
console.log("0" == true)
console.log("1" == 1)
// === without Type Coercion
console.log("Without Type Coercion")
console.log(0 === "0")
console.log(0 === false)
console.log(0 === true)
console.log("0" === false)
console.log("0" === true)
console.log("1" === 1)